// <auto-generated />
namespace ONE_SMALL_STEP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addsourceandsourcetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsourceandsourcetype));
        
        string IMigrationMetadata.Id
        {
            get { return "202001252336381_add-source-and-source-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
