// <auto-generated />
namespace ONE_SMALL_STEP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class date_name_changes_and_view_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(date_name_changes_and_view_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202002050436564_date_name_changes_and_view_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
