// <auto-generated />
namespace ONE_SMALL_STEP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MessageTypetablechangedpublicvirtualICollectiontopublicICollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageTypetablechangedpublicvirtualICollectiontopublicICollection));
        
        string IMigrationMetadata.Id
        {
            get { return "202002160143568_MessageType table -- changed public virtual ICollection to public ICollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
